spring:
  application:
    name: ezeestreaming

  datasource:
    url: jdbc:mysql://localhost:3306/ezee_video_streaming
    username: root
    password: Fortune@0
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
